// FETCH DATA
export const FETCH_PROFILE = "FETCH_PROFILE"
export const FETCH_OWN_FOODPLACE = "FETCH_OWN_FOODPLACE"

// MY PROFILE ACTIONS
export const EDIT_PROFILE = "EDIT_PROFILE"
export const CHECK_USERNAME = "CHECK_USERNAME"
export const CHECK_EMAIL = "CHECK_EMAIL"
export const CHECK_PASSWORD = "CHECK_PASSWORD"
export const SAVE_CHANGES = "SAVE_CHANGES"
export const CANCEL_CHANGES = "CANCEL_CHANGES"
export const DELETE_ACCOUNT = "DELETE_ACCOUNT"

// DASHBOARD ACTIONS
export const EDITING_FOOD_PLACE = "EDITING_FOOD_PLACE"
export const EDIT_FOOD_PLACE = "EDIT_FOOD_PLACE"
export const ADDING_FOOD_PLACE = "ADDING_FOOD_PLACE"
export const ADD_FOOD_PLACE = "ADD_FOOD_PLACE"
export const DELETE_FOOD_PLACE = "DELETE_FOOD_PLACE"

export const UPLOAD_IMAGE = "UPLOAD_IMAGE"