export const FETCH_FOOD_PLACES_REQUEST = "FETCH_FOOD_PLACES_REQUEST"
export const FETCH_FOOD_PLACES_SUCCESS = "FETCH_FOOD_PLACES_SUCCESS"
export const FETCH_FOOD_PLACES_FAILURE = "FETCH_FOOD_PLACES_FAILURE"